"""add_checklist_snapshot_to_compliance

Revision ID: 23a89e8ea2ad
Revises: 3dc2b0b3faa5
Create Date: 2026-04-05 10:01:19.808134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a89e8ea2ad'
down_revision: Union[str, Sequence[str], None] = '3dc2b0b3faa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_snapshots', sa.Column('checklist_snapshot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compliance_snapshots', 'checklist_snapshot')
    # ### end Alembic commands ###
