"""create_all_tables

Revision ID: 3dc2b0b3faa5
Revises: 
Create Date: 2026-04-02 23:22:29.767622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dc2b0b3faa5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', postgresql.ENUM('aws', 'gcp', 'azure', name='scan_provider'), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('credentials', sa.LargeBinary(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'account_id')
    )
    op.create_table('isms_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('config_sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conformance_pack', sa.String(length=200), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'completed', 'failed', 'cancelled', name='scan_status'), nullable=False),
    sa.Column('total_rules', sa.Integer(), nullable=False),
    sa.Column('compliant', sa.Integer(), nullable=False),
    sa.Column('non_compliant', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=300), nullable=False),
    sa.Column('legal_basis', sa.String(length=100), nullable=False),
    sa.Column('data_categories', sa.Text(), nullable=False),
    sa.Column('retention_period', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destruction_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_category', sa.String(length=200), nullable=False),
    sa.Column('data_description', sa.Text(), nullable=True),
    sa.Column('data_volume', sa.String(length=100), nullable=True),
    sa.Column('retention_basis', sa.String(length=200), nullable=True),
    sa.Column('retention_expiry', sa.Date(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('method', sa.String(length=200), nullable=True),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('status', postgresql.ENUM('scheduled', 'in_progress', 'completed', 'verified', 'overdue', name='destruction_status'), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=True),
    sa.Column('verifier_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handler_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dsr_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_type', postgresql.ENUM('access', 'correction', 'deletion', 'suspension', name='dsr_type'), nullable=False),
    sa.Column('requester_name', sa.String(length=100), nullable=False),
    sa.Column('requester_contact', sa.String(length=200), nullable=True),
    sa.Column('requester_id_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('received', 'assigned', 'processing', 'completed', 'rejected', 'overdue', name='dsr_status'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('result_description', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dsr_due_date', 'dsr_requests', ['due_date'], unique=False)
    op.create_index('idx_dsr_status', 'dsr_requests', ['status'], unique=False)
    op.create_table('export_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='export_status'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('severity', postgresql.ENUM('low', 'medium', 'high', 'critical', name='incident_severity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notification_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reportable_to_authority', sa.Boolean(), nullable=False),
    sa.Column('report_threshold_basis', sa.String(length=200), nullable=True),
    sa.Column('illegal_external_access', sa.Boolean(), nullable=False),
    sa.Column('initial_report_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supplemental_report_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subjects_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_exception_reason', sa.Text(), nullable=True),
    sa.Column('website_notice_posted_from', sa.Date(), nullable=True),
    sa.Column('website_notice_posted_to', sa.Date(), nullable=True),
    sa.Column('affected_subjects_count', sa.Integer(), nullable=True),
    sa.Column('data_types_affected', sa.Text(), nullable=True),
    sa.Column('includes_sensitive_data', sa.Boolean(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('detected', 'analyzing', 'containing', 'recovering', 'resolved', 'closed', name='incident_status'), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handler_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('isms_subdomains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['isms_domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_history_user_id'), 'password_history', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('scan_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cloud_account_id', sa.Integer(), nullable=True),
    sa.Column('provider', postgresql.ENUM('aws', 'gcp', 'azure', name='scan_provider'), nullable=False),
    sa.Column('compliance', sa.String(length=100), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'completed', 'failed', 'cancelled', name='scan_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_checks', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('third_party_processors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('business_number', sa.String(length=20), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('data_categories', sa.Text(), nullable=False),
    sa.Column('contract_start', sa.Date(), nullable=False),
    sa.Column('contract_end', sa.Date(), nullable=False),
    sa.Column('is_sub_delegated', sa.Boolean(), nullable=False),
    sa.Column('parent_processor_id', sa.Integer(), nullable=True),
    sa.Column('disclosure_channel', sa.String(length=100), nullable=True),
    sa.Column('disclosure_url', sa.String(length=500), nullable=True),
    sa.Column('disclosure_started_at', sa.Date(), nullable=True),
    sa.Column('is_marketing_delegation', sa.Boolean(), nullable=False),
    sa.Column('contract_file_key', sa.String(length=500), nullable=True),
    sa.Column('required_clauses_checked', sa.Boolean(), nullable=False),
    sa.Column('security_audit_done', sa.Boolean(), nullable=False),
    sa.Column('audit_date', sa.Date(), nullable=True),
    sa.Column('audit_result', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_processor_id'], ['third_party_processors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_third_party_processors_contract_end'), 'third_party_processors', ['contract_end'], unique=False)
    op.create_table('consent_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['consent_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version_number')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_type', postgresql.ENUM('document', 'prowler', 'pipa_record', 'external_link', name='evidence_type'), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('external_url', sa.String(length=1000), nullable=True),
    sa.Column('scan_job_id', sa.Integer(), nullable=True),
    sa.Column('source_module', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'submitted', 'approved', 'rejected', 'expired', 'replaced', name='evidence_status'), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evidence_status', 'evidence', ['status'], unique=False)
    op.create_index(op.f('ix_evidence_valid_to'), 'evidence', ['valid_to'], unique=False)
    op.create_table('incident_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('isms_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subdomain_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_evidence', sa.Text(), nullable=True),
    sa.Column('has_prowler_checks', sa.Boolean(), nullable=False),
    sa.Column('prowler_check_count', sa.Integer(), nullable=False),
    sa.Column('has_config_rules', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subdomain_id'], ['isms_subdomains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('compliance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('assessment_period', sa.String(length=20), nullable=False),
    sa.Column('status', postgresql.ENUM('compliant', 'partial', 'non_compliant', 'not_applicable', name='compliance_level'), nullable=False),
    sa.Column('prowler_passed', sa.Integer(), nullable=False),
    sa.Column('prowler_failed', sa.Integer(), nullable=False),
    sa.Column('prowler_total', sa.Integer(), nullable=False),
    sa.Column('config_compliant', sa.Integer(), nullable=False),
    sa.Column('config_non_compliant', sa.Integer(), nullable=False),
    sa.Column('config_total', sa.Integer(), nullable=False),
    sa.Column('checklist_checked', sa.Integer(), nullable=False),
    sa.Column('checklist_total', sa.Integer(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('evidence_approved', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.Integer(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['isms_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'assessment_period')
    )
    op.create_table('config_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_job_id', sa.Integer(), nullable=False),
    sa.Column('config_rule_name', sa.String(length=200), nullable=False),
    sa.Column('compliance_type', sa.String(length=20), nullable=False),
    sa.Column('resource_type', sa.String(length=200), nullable=True),
    sa.Column('resource_id', sa.String(length=500), nullable=True),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.Column('isms_item_id', sa.Integer(), nullable=True),
    sa.Column('remediation_status', postgresql.ENUM('open', 'in_progress', 'resolved', 'accepted_risk', 'false_positive', name='remediation_status'), nullable=False),
    sa.Column('remediation_notes', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['isms_item_id'], ['isms_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_eval_compliance', 'config_evaluations', ['compliance_type'], unique=False)
    op.create_index('idx_config_eval_isms', 'config_evaluations', ['isms_item_id'], unique=False)
    op.create_index('idx_config_eval_rule', 'config_evaluations', ['config_rule_name'], unique=False)
    op.create_table('corrective_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', postgresql.ENUM('external_audit', 'internal_review', 'prowler', 'config', 'other', name='corrective_source'), nullable=False),
    sa.Column('source_detail', sa.String(length=300), nullable=True),
    sa.Column('isms_item_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_plan', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'in_progress', 'completed', 'verified', 'overdue', name='corrective_status'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['isms_item_id'], ['isms_items.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ca_due_date', 'corrective_actions', ['due_date'], unique=False)
    op.create_index('idx_ca_isms_item', 'corrective_actions', ['isms_item_id'], unique=False)
    op.create_index('idx_ca_status', 'corrective_actions', ['status'], unique=False)
    op.create_table('evidence_item_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('relevance_note', sa.Text(), nullable=True),
    sa.Column('linked_by', sa.Integer(), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['isms_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'item_id')
    )
    op.create_table('isms_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['isms_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('isms_item_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_in_item', sa.String(length=50), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['isms_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'user_id', 'role_in_item')
    )
    op.create_index(op.f('ix_isms_item_assignments_user_id'), 'isms_item_assignments', ['user_id'], unique=False)
    op.create_table('prowler_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.String(length=200), nullable=False),
    sa.Column('check_title', sa.String(length=500), nullable=True),
    sa.Column('status', postgresql.ENUM('PASS', 'FAIL', 'MANUAL', name='finding_status'), nullable=False),
    sa.Column('severity', postgresql.ENUM('informational', 'low', 'medium', 'high', 'critical', name='finding_severity'), nullable=False),
    sa.Column('resource_uid', sa.String(length=500), nullable=True),
    sa.Column('resource_type', sa.String(length=200), nullable=True),
    sa.Column('resource_region', sa.String(length=50), nullable=True),
    sa.Column('resource_details', sa.Text(), nullable=True),
    sa.Column('isms_item_id', sa.Integer(), nullable=True),
    sa.Column('remediation_status', postgresql.ENUM('open', 'in_progress', 'resolved', 'accepted_risk', 'false_positive', name='remediation_status'), nullable=False),
    sa.Column('remediation_notes', sa.Text(), nullable=True),
    sa.Column('remediated_by', sa.Integer(), nullable=True),
    sa.Column('remediated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['isms_item_id'], ['isms_items.id'], ),
    sa.ForeignKeyConstraint(['remediated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_findings_scan_job', 'prowler_findings', ['scan_job_id'], unique=False)
    op.create_index('idx_findings_severity', 'prowler_findings', ['severity'], unique=False)
    op.create_index('idx_findings_status', 'prowler_findings', ['status'], unique=False)
    op.create_index(op.f('ix_prowler_findings_isms_item_id'), 'prowler_findings', ['isms_item_id'], unique=False)
    op.create_table('checklist_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checked_by', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['checked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['checklist_id'], ['isms_checklists.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_id', 'period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_responses')
    op.drop_index(op.f('ix_prowler_findings_isms_item_id'), table_name='prowler_findings')
    op.drop_index('idx_findings_status', table_name='prowler_findings')
    op.drop_index('idx_findings_severity', table_name='prowler_findings')
    op.drop_index('idx_findings_scan_job', table_name='prowler_findings')
    op.drop_table('prowler_findings')
    op.drop_index(op.f('ix_isms_item_assignments_user_id'), table_name='isms_item_assignments')
    op.drop_table('isms_item_assignments')
    op.drop_table('isms_checklists')
    op.drop_table('evidence_item_links')
    op.drop_index('idx_ca_status', table_name='corrective_actions')
    op.drop_index('idx_ca_isms_item', table_name='corrective_actions')
    op.drop_index('idx_ca_due_date', table_name='corrective_actions')
    op.drop_table('corrective_actions')
    op.drop_index('idx_config_eval_rule', table_name='config_evaluations')
    op.drop_index('idx_config_eval_isms', table_name='config_evaluations')
    op.drop_index('idx_config_eval_compliance', table_name='config_evaluations')
    op.drop_table('config_evaluations')
    op.drop_table('compliance_snapshots')
    op.drop_table('isms_items')
    op.drop_table('incident_timeline')
    op.drop_index(op.f('ix_evidence_valid_to'), table_name='evidence')
    op.drop_index('idx_evidence_status', table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('consent_versions')
    op.drop_index(op.f('ix_third_party_processors_contract_end'), table_name='third_party_processors')
    op.drop_table('third_party_processors')
    op.drop_table('scan_jobs')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_history_user_id'), table_name='password_history')
    op.drop_table('password_history')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('isms_subdomains')
    op.drop_table('incidents')
    op.drop_table('export_jobs')
    op.drop_index('idx_dsr_status', table_name='dsr_requests')
    op.drop_index('idx_dsr_due_date', table_name='dsr_requests')
    op.drop_table('dsr_requests')
    op.drop_table('destruction_records')
    op.drop_table('consent_templates')
    op.drop_table('config_sync_jobs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('isms_domains')
    op.drop_table('cloud_accounts')
    # ### end Alembic commands ###
